name: vertx-codegen (5.x-stable)
on:
  push:
    branches:
      - '5.[0-9]+'
  pull_request:
    branches:
      - '5.[0-9]+'
  schedule:
    - cron: '0 5 * * *'
jobs:
  CI-CD:
    uses: ./.github/workflows/ci-cd-5.x.yml
    secrets: inherit
